### ISSUE TITLE
Feature request - ignore keys

### ISSUE THREAD

**Issue by SebastianPodgajny** [semaphoreci/spc#42]
Hi, is it possible to add some kind of syntax to allow semaphore to ignore specific keys in pipeline configuration
example and usecase
https://www.netways.de/en/blog/2019/11/21/gitlab-ci-yaml-write-less-with-anchors-extends-and-hidden-keys/
https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

Currently if I try to use this pattern semaphore will throw this error
```
Unprocessable YAML file.
Error: [{"Schema does not allow additional properties.", "#/.defaults"}]
```

**Comment by lucianoliberti** [comment]
@SebastianPodgajny thanks for this proposal, we'll consider it!
